FROM ubuntu:20.04 as default

# This target bundles assets from other monorepo projects for
# convenient importing in various Dockerfiles. It does not
# provide the protocol build; this allows us to control when
# the protocol gets copied by using docker build arguments
# to set the tag name ":default" versus ":protocol"!

COPY build-temp/nvidia-driver /nvidia-driver
COPY build-temp/fonts /fonts
COPY build-temp/setup-linux-build-environment.sh /setup-linux-build-environment.sh
RUN mkdir protocol

FROM default as protocol

# This target bundles the protocol, for the reasons mentioned above.

COPY build-temp/protocol /protocol
