FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Gimp and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libgimp2.0 \
    gimp \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Gimp GTK theme (see comment in gimprc)
COPY --chown=fractal gimprc /home/fractal/.config/GIMP/2.10/gimprc
COPY gimprc /root/.config/GIMP/2.10/gimprc

# Setup Fractal application symlink
RUN ln -sf "$(which gimp)" /usr/bin/fractal-application
