FROM fractal/base:current-build

# Install Gimp and its dependencies explicitly
RUN apt-get update && apt-get install -y \
    libgimp2.0 \
    gimp \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# Set GIMP GTK theme (see comment in gimprc)
COPY --chown=fractal gimprc /home/fractal/.config/GIMP/2.10/gimprc
COPY gimprc /root/.config/GIMP/2.10/gimprc

# Setup Fractal application symlink
RUN ln -sf $(which gimp) /usr/bin/fractal-application
