FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install TextureLab build dependencies
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    unzip \
    curl \
    nodejs \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add yarn to apt
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install yarn
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    yarn \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Build and install TextureLab Electron app
RUN git clone https://github.com/njbrown/texturelab \
    && cd texturelab \
    && git submodule update --init \
    && yarn install \
    && yarn electron:build \
    && mv dist_electron/linux-unpacked /opt/texturelab \
    && cd .. \
    && rm -rf texturelab \
    && ln -sf /opt/texturelab/texturelab /usr/bin/texturelab

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/texturelab"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/texturelab /usr/bin/fractal-application
