FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Kdenlive dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    software-properties-common \
    libqt5svg5 \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Source Kdenlive repository
RUN add-apt-repository ppa:kdenlive/kdenlive-stable

# Install Kdenlive
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    kdenlive \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create default config paths
RUN su - fractal -c "mkdir -p \
    /home/fractal/.local/share/kdenlive \
    /home/fractal/.config"
RUN su - fractal -c "touch \
    /home/fractal/.config/kdenliverc \
    /home/fractal/.config/kdenlive-layoutsrc"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/kdenlive /usr/bin/fractal-application
