FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Discord dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libgconf-2-4 \
    libappindicator1 \
    libc++1 \
    wget \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Discord
RUN wget -qO /usr/bin/discord.deb "https://discordapp.com/api/download?platform=linux&format=deb" \
    && cd /usr/bin \
    && dpkg -i /usr/bin/discord.deb \
    && rm -rf /usr/bin/discord*.deb

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/discord"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/discord /usr/bin/fractal-application
