FROM fractal/base:current-build

# Install Google Chrome dependencies explicitly
# Note that all installations need to be prefixed by an `apt-get update` to
# prevent certain errors.
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    fonts-liberation \
    xdg-utils \
    && apt-get autoremove -y \
    && apt-get clean  

# Install Google Chrome
# Note that all installations need to be prefixed by an `apt-get update` to
# prevent certain errors.
RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && sed -i '3 s/^/# /' /etc/apt/sources.list \
    && apt-get update && apt-get install --no-install-recommends -y google-chrome-stable \
    && apt-get autoremove -y \
    && apt-get clean 

# Don't ask for default browser
RUN su - fractal -c "mkdir -p /home/fractal/.config/google-chrome \
                     && touch /home/fractal/.config/google-chrome/'First Run'"
                     
# Application startup script
COPY .xinitrc /root/.xinitrc
