FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Krita dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    software-properties-common \
    libqt5svg5 \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Source Krita repository
RUN add-apt-repository ppa:kritalime/ppa

# Install Krita
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    krita \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create default config paths
RUN su - fractal -c "mkdir -p \
    /home/fractal/.local/share/krita \
    /home/fractal/.config"
RUN su - fractal -c "touch \
    /home/fractal/.config/kritadisplayrc \
    /home/fractal/.config/kritarc"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/krita /usr/bin/fractal-application
