FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Godot and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    unzip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Godot parameters
ENV GODOT_VERSION=3.2.3

# Install Godot
RUN wget -qO godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_x11.64.zip \
    && unzip godot.zip \
    && rm godot.zip \
    && mv Godot* /usr/bin/godot

# Create default config paths
RUN su - fractal -c "mkdir -p \
    /home/fractal/.config/godot \
    /home/fractal/.local/godot"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/godot /usr/bin/fractal-application
