FROM fractal/base:current-build

# Install Godot and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    unzip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV GODOT_VERSION=3.2.3

RUN wget -qO godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_x11.64.zip && \
    unzip godot.zip && \
    rm godot.zip && \
    mv Godot* /usr/bin/godot

# Setup Fractal application symlink
RUN ln -sf /usr/bin/godot /usr/bin/fractal-application
