# See stage 0 of the base Dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM fractal/build-assets:$BuildAssetPackage as build-assets
FROM fractal/base:current-build as fractal-browsers-brave

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Brave Browser dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    apt-transport-https \
    curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Brave Browser installer
RUN curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
RUN echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

# Install Brave Browser
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    brave-browser \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set default browser
RUN su - fractal -c \
    "xdg-mime default brave-browser.desktop text/html \
    && xdg-mime default brave-browser.desktop x-scheme-handler/http \
    && xdg-mime default brave-browser.desktop x-scheme-handler/https \
    && xdg-mime default brave-browser.desktop x-scheme-handler/about"

RUN mkdir -p /etc/opt/brave/policies/managed \
    && echo {} \
    # Whitelist streamed URI protocols (zoommtg,slack,spotify,discord)
    | jq '.URLWhitelist=["zoommtg://*","slack://*","spotify://*","discord://*"]' \
    # Disable search suggestions (as a workaround to improve URL bar
    # keyboard input until we can fork the browser and fix it)
    | jq '.SearchSuggestEnabled=false' \
    # Disable background apps (to prevent apps like Superhuman from
    # indefinitely blocking mandelbox shutdown).
    | jq '.BackgroundModeEnabled=false' \
    > /etc/opt/brave/policies/managed/FractalPolicies.json

# Install Brave Browser extensions
COPY install-extensions.sh /usr/bin/install-extensions.sh
RUN chmod +x /usr/bin/install-extensions.sh && /usr/bin/install-extensions.sh

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/BraveSoftware/Brave-Browser"

# Don't show first run popup
RUN su - fractal -c "touch /home/fractal/.config/BraveSoftware/Brave-Browser/'First Run'"

# Install Whist wrapper script to run Brave Browser into /usr/bin
ENV WHIST_COOKIE_UPLOAD_TARGET="brave"
COPY start-brave.sh /usr/bin/start-brave
RUN chmod +x /usr/bin/start-brave && ln -sf /usr/bin/start-brave /usr/bin/fractal-application

# Install Whist Protocol binaries and helper files (if necessary)
COPY --from=build-assets protocol/* /usr/share/fractal/bin/
