export const INITIAL_POINTS = 50
export const SIGNUP_POINTS = 100
export const REFERRAL_POINTS = 300
export const EASTEREGG_POINTS = 50

// js sets are bugged
export const SECRET_POINTS = {
    LANDING_NO_GPU_NO_PROBLEM: "LANDING_NO_GPU_NO_PROBLEM",
    ABOUT_HOW_IT_WORKS: "ABOUT_HOW_IT_WORKS",
    FOOTER_SUPER_SECRET: "FOOTER_SUPER_SECRET",
}
