from enum import Enum


class MandelboxHostState(str, Enum):
    PRE_CONNECTION = "PRE_CONNECTION"
    ACTIVE = "ACTIVE"
    HOST_SERVICE_UNRESPONSIVE = "HOST_SERVICE_UNRESPONSIVE"
    DRAINING = "DRAINING"
