FROM fractal/base:current-build

RUN echo "deb http://security.ubuntu.com/ubuntu xenial-security main" >> /etc/apt/sources.list

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	libldap-2.4-2 \
	libjack0 \
	libssl1.0.0 \
	wget \
	&& apt-get autoremove -y \
	&& apt-get clean

# Note that this is NOT the latest version of Lightworks -- it is an older version which works on Ubuntu 20.04
# It would be ideal to get the latest version to work, but it may not be possible for some time
RUN wget https://downloads.lwks.com/v14-5/lightworks-14.5.0-amd64.deb -O "lightworks.deb"

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	./lightworks.deb \
	&& apt-get autoremove -y \
	&& apt-get clean

# Setup Fractal application symlink
RUN ln -sf /usr/bin/lightworks /usr/bin/fractal-application
