FROM fractal/base:current-build

RUN echo "deb http://security.ubuntu.com/ubuntu xenial-security main" >> /etc/apt/sources.list

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	libldap-2.4-2 \
	libjack0 \
	libssl1.0.0 \
	wget \
	&& apt-get autoremove -y \
	&& apt-get clean

RUN wget https://downloads.lwks.com/v14-5/lightworks-14.5.0-amd64.deb -O "lightworks.deb"

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	./lightworks.deb \
	&& apt-get autoremove -y \
	&& apt-get clean

# Setup Fractal application symlink
RUN ln -sf /usr/bin/lightworks /usr/bin/fractal-application
