FROM fractal/base:current-build

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    freecad \
    && apt-get autoremove -y \
    && apt-get clean

# Setup Fractal application symlink
RUN ln -sf /usr/bin/freecad /usr/bin/fractal-application
