FROM fractal/base:current-build

# Install FreeCAD and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    freecad \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Setup Fractal application symlink
RUN ln -sf /usr/bin/freecad /usr/bin/fractal-application
