FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Inkscape and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    inkscape \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Setup Fractal application symlink
RUN ln -sf /usr/bin/inkscape /usr/bin/fractal-application
