FROM fractal/base:current-build

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    inkscape \
    && apt-get autoremove -y \
    && apt-get clean 

RUN ln -sf /usr/bin/inkscape /usr/bin/fractal-application
