export const ONBOARDED = "data.onboarded"
export const RESTORE_LAST_SESSION = "data.restoreLastSession"
export const EXIT_TYPEFORM_SUBMITTED = "data.exitTypeformSubmitted"
export const CACHED_ACCESS_TOKEN = "auth.accessToken"
export const CACHED_REFRESH_TOKEN = "auth.refreshToken"
export const CACHED_CONFIG_TOKEN = "auth.configToken"
export const CACHED_USER_EMAIL = "auth.userEmail"
