// Code generated by pggen. DO NOT EDIT.

package queries

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
)

const heartbeatSQL = `UPDATE hardware.instance_info SET
  (memory_remaining_kb, nanocpus_remaining, gpu_vram_remaining_kb, last_updated_utc_unix_ms) =
  ($1, $2, $3, $4)
  WHERE instance_name = $5;`

type HeartbeatParams struct {
	MemoryRemainingKB    int
	NanoCPUsRemainingKB  int
	GpuVramRemainingKb   int
	LastUpdatedUtcUnixMs int
	InstanceName         string
}

// Heartbeat implements Querier.Heartbeat.
func (q *DBQuerier) Heartbeat(ctx context.Context, params HeartbeatParams) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "Heartbeat")
	cmdTag, err := q.conn.Exec(ctx, heartbeatSQL, params.MemoryRemainingKB, params.NanoCPUsRemainingKB, params.GpuVramRemainingKb, params.LastUpdatedUtcUnixMs, params.InstanceName)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query Heartbeat: %w", err)
	}
	return cmdTag, err
}

// HeartbeatBatch implements Querier.HeartbeatBatch.
func (q *DBQuerier) HeartbeatBatch(batch *pgx.Batch, params HeartbeatParams) {
	batch.Queue(heartbeatSQL, params.MemoryRemainingKB, params.NanoCPUsRemainingKB, params.GpuVramRemainingKb, params.LastUpdatedUtcUnixMs, params.InstanceName)
}

// HeartbeatScan implements Querier.HeartbeatScan.
func (q *DBQuerier) HeartbeatScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec HeartbeatBatch: %w", err)
	}
	return cmdTag, err
}
