package queries // import "github.com/fractal/fractal/ecs-host-service/dbdriver/queries"

import (
	_ "github.com/jackc/pgconn"
	_ "github.com/jackc/pgtype"
	_ "github.com/jackc/pgx/v4"
)

// This is a placeholder file to ensure that the host service Makefile still
// works without any autogenerated code in this directory. Besides this file
// (queries.go), all other go files in this directory are autogenerated!
