// Code generated by pggen. DO NOT EDIT.

package queries

import (
	"context"
	"fmt"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

const verifyContainerSQL = `SELECT * FROM hardware.container_info
  WHERE instance_name = $1
    AND user_id = $2;`

type VerifyContainerRow struct {
	ContainerID  pgtype.Varchar `json:"container_id"`
	UserID       pgtype.Varchar `json:"user_id"`
	InstanceName pgtype.Varchar `json:"instance_name"`
	Status       pgtype.Varchar `json:"status"`
}

// VerifyContainer implements Querier.VerifyContainer.
func (q *DBQuerier) VerifyContainer(ctx context.Context, instanceName string, userID string) ([]VerifyContainerRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "VerifyContainer")
	rows, err := q.conn.Query(ctx, verifyContainerSQL, instanceName, userID)
	if err != nil {
		return nil, fmt.Errorf("query VerifyContainer: %w", err)
	}
	defer rows.Close()
	items := []VerifyContainerRow{}
	for rows.Next() {
		var item VerifyContainerRow
		if err := rows.Scan(&item.ContainerID, &item.UserID, &item.InstanceName, &item.Status); err != nil {
			return nil, fmt.Errorf("scan VerifyContainer row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close VerifyContainer rows: %w", err)
	}
	return items, err
}

// VerifyContainerBatch implements Querier.VerifyContainerBatch.
func (q *DBQuerier) VerifyContainerBatch(batch *pgx.Batch, instanceName string, userID string) {
	batch.Queue(verifyContainerSQL, instanceName, userID)
}

// VerifyContainerScan implements Querier.VerifyContainerScan.
func (q *DBQuerier) VerifyContainerScan(results pgx.BatchResults) ([]VerifyContainerRow, error) {
	rows, err := results.Query()
	if err != nil {
		return nil, fmt.Errorf("query VerifyContainerBatch: %w", err)
	}
	defer rows.Close()
	items := []VerifyContainerRow{}
	for rows.Next() {
		var item VerifyContainerRow
		if err := rows.Scan(&item.ContainerID, &item.UserID, &item.InstanceName, &item.Status); err != nil {
			return nil, fmt.Errorf("scan VerifyContainerBatch row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close VerifyContainerBatch rows: %w", err)
	}
	return items, err
}
