# See stage 0 of the base Dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM whist/build-assets:$BuildAssetPackage as build-assets
FROM whisthq/base:current-build as whist-ming-test-app

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

COPY Whist.deb /

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    /Whist.deb \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm /Whist.deb


# Install Whist wrapper script to run ming-test-app into /usr/bin
COPY start-ming-test-app.sh /usr/bin/start-ming-test-app
RUN chmod +x /usr/bin/start-ming-test-app && ln -sf /opt/whist/whist /usr/bin/whist-application

# Install Whist Protocol binaries and helper files (if necessary)
COPY --from=build-assets protocol/* /usr/share/whist/bin/
