export enum FractalIPC {
    SHOW_MAIN_WINDOW = "showMainWindow",
    LOAD_BROWSER = "loadBrowser",
    CLOSE_BROWSER = "closeBrowser",
    GET_ENCRYPTION_KEY = "getEncryptionKey",
    FORCE_QUIT = "forceQuit",
    UPDATE = "update",
    CUSTOM_URL = "customURL",
    PERCENT_DOWNLOADED = "percent",
    DOWNLOAD_SPEED = "download-speed",
    TOTAL_DOWNLOADED = "total",
    DOWNLOAD_ERROR = "error",
    PERCENT_TRANSFERRED = "transferred",
    DOWNLOADED = "downloaded",
}
