export enum FractalIPC {
    SHOW_MAIN_WINDOW = "showMainWindow",
    LOAD_BROWSER = "loadBrowser",
    CLOSE_OTHER_WINDOWS = "closeOtherWindows",
    FORCE_QUIT = "forceQuit",
    UPDATE = "update",
    CUSTOM_URL = "customURL",
    PERCENT_DOWNLOADED = "percent",
    DOWNLOAD_SPEED = "download-speed",
    TOTAL_DOWNLOADED = "total",
    DOWNLOAD_ERROR = "error",
    PERCENT_TRANSFERRED = "transferred",
    DOWNLOADED = "downloaded",
    KILL_RENDER_THREAD = "killRenderThread",
    TEST_LOG = "testLog",
    SET_USERID = "setUserID",
    LAUNCH_PROTOCL = "launchProtocol",
    SEND_CONTAINER = "sendContainer",
}
