# CMake generated Testfile for 
# Source directory: C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests
# Build directory: C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test1 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test1.test")
  set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test1 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test1.test")
  set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test1 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test1.test")
  set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test1 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test1.test")
  set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test2 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test2.test")
  set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test2 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test2.test")
  set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test2 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test2.test")
  set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test2 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test2.test")
  set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test4 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test4.test")
  set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test4 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test4.test")
  set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test4 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test4.test")
  set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test4 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test4.test")
  set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testReplaceExisting "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/testReplaceExisting.test")
  set_tests_properties(testReplaceExisting PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testReplaceExisting "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/testReplaceExisting.test")
  set_tests_properties(testReplaceExisting PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testReplaceExisting "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/testReplaceExisting.test")
  set_tests_properties(testReplaceExisting PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testReplaceExisting "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/testReplaceExisting.test")
  set_tests_properties(testReplaceExisting PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(testReplaceExisting NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_cast "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_cast.test")
  set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_cast "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_cast.test")
  set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_cast "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_cast.test")
  set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_cast "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_cast.test")
  set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_charcase "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_charcase.test")
  set_tests_properties(test_charcase PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_charcase "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_charcase.test")
  set_tests_properties(test_charcase PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_charcase "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_charcase.test")
  set_tests_properties(test_charcase PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_charcase "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_charcase.test")
  set_tests_properties(test_charcase PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_charcase NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_compare "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_compare.test")
  set_tests_properties(test_compare PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_compare "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_compare.test")
  set_tests_properties(test_compare PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_compare "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_compare.test")
  set_tests_properties(test_compare PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_compare "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_compare.test")
  set_tests_properties(test_compare PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_compare NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_deep_copy "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_deep_copy.test")
  set_tests_properties(test_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_deep_copy "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_deep_copy.test")
  set_tests_properties(test_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_deep_copy "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_deep_copy.test")
  set_tests_properties(test_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_deep_copy "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_deep_copy.test")
  set_tests_properties(test_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_deep_copy NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_double_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_double_serializer.test")
  set_tests_properties(test_double_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_double_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_double_serializer.test")
  set_tests_properties(test_double_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_double_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_double_serializer.test")
  set_tests_properties(test_double_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_double_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_double_serializer.test")
  set_tests_properties(test_double_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_double_serializer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_float "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_float.test")
  set_tests_properties(test_float PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_float "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_float.test")
  set_tests_properties(test_float PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_float "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_float.test")
  set_tests_properties(test_float PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_float "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_float.test")
  set_tests_properties(test_float PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_float NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_int_add "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_int_add.test")
  set_tests_properties(test_int_add PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_int_add "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_int_add.test")
  set_tests_properties(test_int_add PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_int_add "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_int_add.test")
  set_tests_properties(test_int_add PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_int_add "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_int_add.test")
  set_tests_properties(test_int_add PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_int_add NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_json_pointer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_json_pointer.test")
  set_tests_properties(test_json_pointer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_json_pointer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_json_pointer.test")
  set_tests_properties(test_json_pointer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_json_pointer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_json_pointer.test")
  set_tests_properties(test_json_pointer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_json_pointer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_json_pointer.test")
  set_tests_properties(test_json_pointer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_json_pointer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_locale "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_locale.test")
  set_tests_properties(test_locale PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_locale "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_locale.test")
  set_tests_properties(test_locale PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_locale "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_locale.test")
  set_tests_properties(test_locale PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_locale "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_locale.test")
  set_tests_properties(test_locale PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_locale NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_null "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_null.test")
  set_tests_properties(test_null PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_null "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_null.test")
  set_tests_properties(test_null PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_null "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_null.test")
  set_tests_properties(test_null PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_null "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_null.test")
  set_tests_properties(test_null PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_null NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_parse "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse.test")
  set_tests_properties(test_parse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_parse "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse.test")
  set_tests_properties(test_parse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_parse "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse.test")
  set_tests_properties(test_parse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_parse "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse.test")
  set_tests_properties(test_parse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_parse NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_parse_int64 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse_int64.test")
  set_tests_properties(test_parse_int64 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_parse_int64 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse_int64.test")
  set_tests_properties(test_parse_int64 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_parse_int64 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse_int64.test")
  set_tests_properties(test_parse_int64 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_parse_int64 "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_parse_int64.test")
  set_tests_properties(test_parse_int64 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_parse_int64 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_printbuf "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_printbuf.test")
  set_tests_properties(test_printbuf PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_printbuf "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_printbuf.test")
  set_tests_properties(test_printbuf PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_printbuf "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_printbuf.test")
  set_tests_properties(test_printbuf PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_printbuf "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_printbuf.test")
  set_tests_properties(test_printbuf PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_printbuf NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_set_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_serializer.test")
  set_tests_properties(test_set_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_set_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_serializer.test")
  set_tests_properties(test_set_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_set_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_serializer.test")
  set_tests_properties(test_set_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_set_serializer "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_serializer.test")
  set_tests_properties(test_set_serializer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_set_serializer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_set_value "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_value.test")
  set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_set_value "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_value.test")
  set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_set_value "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_value.test")
  set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_set_value "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_set_value.test")
  set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_set_value NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_util_file "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_util_file.test")
  set_tests_properties(test_util_file PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_util_file "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_util_file.test")
  set_tests_properties(test_util_file PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_util_file "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_util_file.test")
  set_tests_properties(test_util_file PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_util_file "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_util_file.test")
  set_tests_properties(test_util_file PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_util_file NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_visit "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_visit.test")
  set_tests_properties(test_visit PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_visit "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_visit.test")
  set_tests_properties(test_visit PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_visit "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_visit.test")
  set_tests_properties(test_visit PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_visit "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/test_visit.test")
  set_tests_properties(test_visit PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;39;add_test;C:/Users/vm1/Downloads/fractal-protocol/desktop/include/json-c/tests/CMakeLists.txt;0;")
else()
  add_test(test_visit NOT_AVAILABLE)
endif()
