FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Darktable and its dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    darktable \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/darktable"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/darktable /usr/bin/fractal-application
