FROM fractal/base:current-build

RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    darktable \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Setup Fractal application symlink
RUN ln -sf /usr/bin/darktable /usr/bin/fractal-application
