# See stage 0 of the base dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM whist/build-assets:$BuildAssetPackage as build-assets
FROM whisthq/base:current-build as whist-development-client

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install build utilities
RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-dev \
    gcc \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*

# Install utility for sending input events via Python
RUN pip install --no-cache-dir pynput

# Replace WhistServer startup scripts with WhistClient startup scripts
RUN rm /usr/share/whist/run-whist-server.sh

# Enable proper scripts and services for Whist client
COPY --chmod=555 run-whist-client.sh /usr/share/whist/run-whist-client.sh

COPY mouse_events.py /usr/share/whist/mouse_events.py

COPY --chown=root:root --chmod=600 whist-main.service /etc/systemd/system
RUN systemctl enable whist-main

# If needed, install WhistServer and helpers. Must be last step.
COPY --from=build-assets protocol/* /usr/share/whist/
