FROM fractal/base:current-build as fractal-browsers-chrome

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Replace startup scripts
RUN rm /usr/share/fractal/run-fractal-server.sh
COPY development/client/run-fractal-client.sh /usr/share/fractal/run-fractal-client.sh
RUN chmod +x /usr/share/fractal/run-fractal-client.sh
COPY main/fractal-main.service /etc/systemd/system
RUN systemctl enable fractal-main
