FROM fractal/base:current-build

# Install R Studio dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    r-base \
    libclang-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set R Studio parameters
# We set R Studio a specific distro because they don't officially support focal (Ubuntu 20.04)
ENV RSTUDIO_VERSION=1.3.1093
ENV RSTUDIO_ARCH=amd64
ENV RSTUDIO_DISTRO=bionic
 
# Install R Studio
RUN wget -qO rstudio.deb "https://download1.rstudio.org/desktop/${RSTUDIO_DISTRO}/${RSTUDIO_ARCH}/rstudio-${RSTUDIO_VERSION}-${RSTUDIO_ARCH}.deb" \
    && dpkg -i rstudio.deb \
    && rm rstudio.deb

# Setup Fractal application symlink
RUN ln -sf /usr/bin/rstudio /usr/bin/fractal-application
