FROM ubuntu:18.04
RUN yes | unminimize
ENV container docker
ENV LC_ALL C
# ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/# deb/deb/g' /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y systemd systemd-sysv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN cd /lib/systemd/system/sysinit.target.wants/ \
    && ls | grep -v systemd-tmpfiles-setup | xargs rm -f $1

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/* \
    /lib/systemd/system/plymouth* \
    /lib/systemd/system/systemd-update-utmp*

RUN apt-get update && apt-get clean && apt-get install -y \
    x11vnc \
    xvfb \
    fluxbox \
    wmctrl \
    wget \
    gnupg2 \
    libgbm1 \
    libxcb-dri3-0 \
    wget \
    python \
    python3 \
    gnupg2 \
    sudo \
    vim \
    apt-utils \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update && apt-get -y install google-chrome-stable \
    && apt-get clean

# Avoids interactive installation for tzdata
# Uses UTC
ENV LOCAL="yes"
RUN apt-get -y install tzdata keyboard-configuration ufw

# Workaround for sudo bug in containers https://github.com/sudo-project/sudo/issues/42
RUN echo "Set disable_coredump false" >> /etc/sudo.conf

# RUN wget -q -O utils.sh https://fractal-cloud-setup-s3bucket.s3.amazonaws.com/utils.sh >>/dev/null 2>&1
# Using local setup-scripts repository for development
ADD setup-scripts /setup-scripts

RUN useradd --create-home fractal \
    && usermod -aG sudo fractal \
    && echo 'fractal:password1234567.' | chpasswd

RUN apt-get install lsb-release -y && apt-get clean
RUN apt-get install -y pulseaudio
# Install all required components for Fractal to perform well
# Split into multiple steps for caching
WORKDIR /setup-scripts/linux
RUN /bin/bash -c "source utils.sh \
    && Update-Linux \
    && Set-Time \
    && Install-VirtualDisplay"
RUN /bin/bash -c "source utils.sh \
    && Install-7Zip \
    && Install-Curl \
    && Install-GoogleChrome"
RUN /bin/bash -c "source utils.sh \
    && Install-NvidiaTeslaPublicDrivers \
    && Disable-TCC \
    && Set-OptimalGPUSettings"
RUN /bin/bash -c "source utils.sh \
    && Install-CustomX11Configuration"
RUN /bin/bash -c "source utils.sh \
    && Set-FractalDirectory \
    && Install-FractalServer dev"
# RUN /bin/bash -c "source utils.sh \ 
#     && Install-FractalExitScript"
RUN /bin/bash -c "source utils.sh \
    && Install-FractalAutoUpdate master"
RUN /bin/bash -c "source utils.sh \
    && Install-FractalLinuxInputDriver"
# RUN /bin/bash -c "source utils.sh \
#     && Install-FractalWallpaper"
RUN /bin/bash -c "source utils.sh \
    && Install-Unison \
    && Enable-SSHKey"
RUN /bin/bash -c " source utils.sh \
    && Disable-Shutdown"
RUN /bin/bash -c " source utils.sh \
    && Add-AutoLogin \
    && Disable-AutomaticLockScreen"
RUN /bin/bash -c " source utils.sh \
    Install-FractalServer \
    Install-CustomGDMConfiguration"
WORKDIR /

#From protocol/server/linux-server-setup.sh
RUN sudo apt-get install ffmpeg libavcodec-dev libavdevice-dev libx11-dev libxtst-dev libxdamage-dev libasound2-dev xclip x11-xserver-utils -y
ADD bootstrap.sh /home/fractal
ADD entry.sh /home/fractal
ADD display-service-envs /home/fractal
ADD fractal-input.rules home/fractal

RUN chmod +x /home/fractal/bootstrap.sh \
    && chown -v -R fractal:fractal /home/fractal
RUN chown root:root /run/user
RUN chmod +x /home/fractal/entry.sh


ADD fractal-entrypoint.service /etc/systemd/system
ADD fractal-display.service /etc/systemd/system
ADD fractal-protocol.service /etc/systemd/system
# RUN chmod u+x /etc/systemd/system/bootstrap-service.service

VOLUME [ "/sys/fs/cgroup" ]

RUN sudo apt-get install -y openssh-server
RUN systemctl enable ssh

#As opposed to graphical.target, which is the default
#RUN systemctl set-default multi-user.target
ENV init /sbin/init
RUN systemctl enable fractal-entrypoint
RUN systemctl enable fractal-display
RUN systemctl enable fractal-protocol
# RUN chmod +x /lib/systemd/systemd

ADD fractal-setup.sh /
RUN chmod +x /fractal-setup.sh

# USER fractal
#ENTRYPOINT ["/usr/bin/sudo"]
CMD ["/lib/systemd/systemd"]
# CMD ["/home/fractal/bootstrap.sh"]