FROM fractal/browsers/chrome:current-build

RUN apt-get update && apt-get install --allow-downgrades -y \
    dbus-x11 \
    gconf-service-backend \
    gconf-service \
    libc6 \
    libgconf-2-4 \
    libglib2.0-0 \
    libxml2 \
    psmisc \
    python \
    gconf2 \
    python3 \
    gvfs-common \
    gvfs \
    gvfs-bin \
    && apt-get autoremove -y \
    && apt-get clean

RUN wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb -O /tmp/slack-desktop-4.0.2-amd64.deb && \
    cd /tmp/ && \
    dpkg -i slack-desktop-4.0.2-amd64.deb && \
    rm -rf /tmp/slack-desktop*.deb

# Application startup script
COPY .xinitrc /root/.xinitrc
