FROM fractal/browsers/chrome:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Slack dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libappindicator1 \
    dbus-x11 \
    gconf-service-backend \
    gconf-service \
    libc6 \
    libgconf-2-4 \
    libglib2.0-0 \
    libxml2 \
    psmisc \
    python \
    gconf2 \
    python3 \
    gvfs-common \
    gvfs \
    gvfs-bin \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download and install Slack
RUN wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb -qO /tmp/slack-desktop-4.0.2-amd64.deb \
    && cd /tmp/ \
    && dpkg -i slack-desktop-4.0.2-amd64.deb \
    && rm -rf /tmp/slack-desktop*.deb

# Install Fractal wrapper script to run Slack into /usr/bin
RUN rm /usr/bin/slack
COPY run-slack.sh /usr/bin/slack
RUN chmod +x /usr/bin/slack

# Whitelist slack:// in Google Chrome, for authentication redirection
RUN mkdir -p /etc/opt/chrome/policies/managed \
    && echo {} \
    | jq '.URLWhitelist=["slack://*"]' \
    > /etc/opt/chrome/policies/managed/whitelist.json

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/Slack"

# Setup Fractal application symlink
RUN ln -sf /usr/bin/slack /usr/bin/fractal-application
