// Code generated by pggen. DO NOT EDIT.

package queries

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
)

const removeMandelboxSQL = `DELETE FROM hardware.mandelbox_info WHERE mandelbox_id = $1;`

// RemoveMandelbox implements Querier.RemoveMandelbox.
func (q *DBQuerier) RemoveMandelbox(ctx context.Context, mandelboxID string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "RemoveMandelbox")
	cmdTag, err := q.conn.Exec(ctx, removeMandelboxSQL, mandelboxID)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query RemoveMandelbox: %w", err)
	}
	return cmdTag, err
}

// RemoveMandelboxBatch implements Querier.RemoveMandelboxBatch.
func (q *DBQuerier) RemoveMandelboxBatch(batch genericBatch, mandelboxID string) {
	batch.Queue(removeMandelboxSQL, mandelboxID)
}

// RemoveMandelboxScan implements Querier.RemoveMandelboxScan.
func (q *DBQuerier) RemoveMandelboxScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec RemoveMandelboxBatch: %w", err)
	}
	return cmdTag, err
}
