// Code generated by pggen. DO NOT EDIT.

package queries

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

const writeInstanceStatusSQL = `UPDATE hardware.instance_info
  SET status = $1
  WHERE instance_name = $2;`

// WriteInstanceStatus implements Querier.WriteInstanceStatus.
func (q *DBQuerier) WriteInstanceStatus(ctx context.Context, status pgtype.Varchar, instanceName string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "WriteInstanceStatus")
	cmdTag, err := q.conn.Exec(ctx, writeInstanceStatusSQL, status, instanceName)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query WriteInstanceStatus: %w", err)
	}
	return cmdTag, err
}

// WriteInstanceStatusBatch implements Querier.WriteInstanceStatusBatch.
func (q *DBQuerier) WriteInstanceStatusBatch(batch genericBatch, status pgtype.Varchar, instanceName string) {
	batch.Queue(writeInstanceStatusSQL, status, instanceName)
}

// WriteInstanceStatusScan implements Querier.WriteInstanceStatusScan.
func (q *DBQuerier) WriteInstanceStatusScan(results pgx.BatchResults) (pgconn.CommandTag, error) {
	cmdTag, err := results.Exec()
	if err != nil {
		return cmdTag, fmt.Errorf("exec WriteInstanceStatusBatch: %w", err)
	}
	return cmdTag, err
}
