# See stage 0 of the base dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM whist/build-assets:$BuildAssetPackage as build-assets
FROM whisthq/browsers/chrome:current-build as whist-development-xterm

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install xterm and dependencies
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libc6 \
    libfontconfig1 \
    libfreetype6 \
    libice6 \
    libtinfo6 \
    libutempter0 \
    libx11-6 \
    libxaw7 \
    libxext6 \
    libxft2 \
    libxinerama1 \
    libxmu6 \
    libxpm4 \
    libxt6 \
    xbitmaps \
    x11-utils \
    xterm \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*

# Set up the xterm Whist application symlink
RUN ln -sf "$(which xterm)" /usr/bin/whist-application

# If needed, install WhistServer and helpers. Must be last step.
COPY --from=build-assets protocol/* /usr/share/whist/bin/
