FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Brave Browser dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    apt-transport-https \
    curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Brave Browser installer
RUN curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
RUN echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

# Install Brave Browser
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    brave-browser \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Brave Browser extensions
COPY install-extensions.sh /usr/bin/install-extensions.sh
RUN chmod +x /usr/bin/install-extensions.sh
RUN /usr/bin/install-extensions.sh

# Setup Fractal application symlink
RUN ln -sf $(which brave-browser) /usr/bin/fractal-application
