FROM fractal/base:current-build

# Install Blockbench dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	wget \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Blockbench installer
RUN wget https://github.com/JannisX11/blockbench/releases/download/v3.6.6/Blockbench_3.6.6.deb -O Blockbench_3.6.6.deb

# Install Blockbench
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
	./Blockbench_3.6.6.deb \
    && rm Blockbench_3.6.6.deb \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Setup Fractal application symlink
RUN ln -sf /usr/bin/blockbench /usr/bin/fractal-application
