FROM fractal/base:current-build

RUN apt-get update && \
	apt-get install -y \
	curl \
	libfreetype6 \
	libxi6 \
	libxrender1 \
	unzip \
	xz-utils \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV BLENDER_VERSION 2.82
ENV BLENDER_VERSION_FULL ${BLENDER_VERSION}a
ENV BLENDER_URL https://download.blender.org/release/Blender${BLENDER_VERSION}/blender-${BLENDER_VERSION_FULL}-linux64.tar.xz

RUN curl -L ${BLENDER_URL} | tar -xJ -C /usr/local/ && \
	mv /usr/local/blender-${BLENDER_VERSION_FULL}-linux64 /usr/local/blender


# Install our default config
COPY userpref.blend /home/fractal/.config/blender/${BLENDER_VERSION}/userpref.blend

RUN wget -P /usr/local/ https://cloud.blender.org/r/downloads/blender_cloud-latest-addon.zip && unzip /usr/local/blender_cloud-latest-addon.zip

# Setup Fractal application symlink
RUN ln -sf /usr/local/blender/blender /usr/bin/fractal-application
