export enum Storage {
  AUTH_INFO = "AUTH_INFO",
  CLOSEST_AWS_REGIONS = "CLOSEST_AWS_REGIONS",
  CONFIG_TOKEN_INFO = "CONFIG_TOKEN_INFO",
  SAVED_CLOUD_URLS = "SAVED_CLOUD_URLS",
  WAITLISTED = "WAITLISTED",
}

export enum MandelboxState {
  MANDELBOX_NONEXISTENT,
  MANDELBOX_WAITING,
  MANDELBOX_CONNECTED,
}
