FROM fractal/base:current-build

# Install Google Chrome dependencies explicitly
# Note that all installations need to be prefixed by an `apt-get update` to
# prevent certain errors.
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    tar \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    fonts-liberation \
    xdg-utils \
    xdg-utils \
    dmg2img \
    p7zip-full \
    && apt-get autoremove -y \
    && apt-get clean 

# Install Google Chrome
# Note that all installations need to be prefixed by an `apt-get update` to
# prevent certain errors.
RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && sed -i '3 s/^/# /' /etc/apt/sources.list \
    && apt-get update && apt-get install --allow-downgrades -y google-chrome-stable

ENV NOTION_VERSION 2.0.8
ENV ELECTRON_VERSION v6.1.12

RUN wget -qO "/usr/bin/electron-$ELECTRON_VERSION-linux-x64.zip" "https://github.com/electron/electron/releases/download/$ELECTRON_VERSION/electron-$ELECTRON_VERSION-linux-x64.zip" 
RUN wget -qO "/usr/bin/notion-$NOTION_VERSION.dmg" "https://desktop-release.notion-static.com/Notion-$NOTION_VERSION.dmg"
RUN dmg2img  "/usr/bin/notion-$NOTION_VERSION.dmg" "/usr/bin/notion-$NOTION_VERSION.img"

RUN rm -rf tmp/build 2>/usr/bin/null || true
RUN mkdir -p tmp/build 2>/usr/bin/null || true

RUN set -x && 7z x "/usr/bin/electron-$ELECTRON_VERSION-linux-x64.zip" -y -otmp/build >/usr/bin/null \
    && 7z x "/usr/bin/notion-$NOTION_VERSION.img" -y  -otmp/notion >/usr/bin/null

RUN cp -r tmp/notion/Notion**/*.app/Contents/Resources/* tmp/build 
RUN cp -r tmp/notion tmp/build
RUN rm -rf release/* \
    && 7z a "release/notion-$NOTION_VERSION.tar" tmp/build \
    && 7z rn "release/notion-$NOTION_VERSION.tar" tmp/build "notion-$NOTION_VERSION" \
    && xz --threads=0 "release/notion-$NOTION_VERSION.tar"

RUN set +x
RUN tar xf "release/notion-$NOTION_VERSION.tar.xz" -C tmp
RUN mv "tmp/notion-$NOTION_VERSION" /opt/notion
COPY run-notion.sh /usr/bin/notion
RUN chmod +x /usr/bin/notion

COPY .xinitrc /root/.xinitrc
