FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Download Sidekick installer
RUN wget -qO sidekick.deb https://api.meetsidekick.com/downloads/df/linux/deb

# Install Sidekick
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    ./sidekick.deb \
    && rm sidekick.deb \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set as default browser
RUN su - fractal -c \
    "xdg-mime default sidekick-browser.desktop text/html \
    && xdg-mime default sidekick-browser.desktop x-scheme-handler/http \
    && xdg-mime default sidekick-browser.desktop x-scheme-handler/https \
    && xdg-mime default sidekick-browser.desktop x-scheme-handler/about"

# Don't show first run popup
RUN su - fractal -c "mkdir -p /home/fractal/.config/sidekick \
    && touch /home/fractal/.config/sidekick/'First Run'"

# Setup Fractal application symlink
RUN ln -sf $(which sidekick-browser) /usr/bin/fractal-application
