add_test( ClientTest.EqualityTest /Users/phil/Downloads/fractal/protocol/test/FractalClientTest [==[--gtest_filter=ClientTest.EqualityTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ClientTest.EqualityTest PROPERTIES WORKING_DIRECTORY /Users/phil/Downloads/fractal/protocol/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ClientTest.NotEqualityTest /Users/phil/Downloads/fractal/protocol/test/FractalClientTest [==[--gtest_filter=ClientTest.NotEqualityTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ClientTest.NotEqualityTest PROPERTIES WORKING_DIRECTORY /Users/phil/Downloads/fractal/protocol/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ClientTest.ArgParsingEmptyArgsTest /Users/phil/Downloads/fractal/protocol/test/FractalClientTest [==[--gtest_filter=ClientTest.ArgParsingEmptyArgsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ClientTest.ArgParsingEmptyArgsTest PROPERTIES WORKING_DIRECTORY /Users/phil/Downloads/fractal/protocol/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ClientTest.FractalColorTest /Users/phil/Downloads/fractal/protocol/test/FractalClientTest [==[--gtest_filter=ClientTest.FractalColorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ClientTest.FractalColorTest PROPERTIES WORKING_DIRECTORY /Users/phil/Downloads/fractal/protocol/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( FractalClientTest_TESTS ClientTest.EqualityTest ClientTest.NotEqualityTest ClientTest.ArgParsingEmptyArgsTest ClientTest.FractalColorTest)
