FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Firefox dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libatk1.0-0 \
    libc6 \
    libcairo-gobject2 \
    libcairo2 \
    libdbus-1-3 \
    libdbus-glib-1-2 \
    libffi7 \
    libfontconfig1 \
    libfreetype6 \
    libgcc-s1 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libharfbuzz0b \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpangoft2-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb-shm0 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrender1 \
    libxt6 \
    lsb-release \
    libcanberra0 \
    libdbusmenu-glib4 \
    libdbusmenu-gtk3-4 \
    xul-ext-ubufox \
    fonts-lyx \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Firefox
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    firefox \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Firefox extensions 
# To install new Firefox extensions, first wget the file from Mozilla and then move it to /usr/share/mozilla/extensions
# i.e.:
# RUN wget -P "/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/" "https://addons.mozilla.org/firefox/downloads/file/3663488/ublock_origin-1.30.6-an+fx.xpi"
# RUN mv "/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ublock_origin-1.30.6-an+fx.xpi" "/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/uBlock0@raymondhill.net.xpi"

# Use precise scrolling
RUN echo export MOZ_USE_XINPUT2=1 | tee /etc/profile.d/use-xinput2.sh

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.mozilla/firefox"

# Copy custom user profile
COPY fractal_profile/  /home/fractal/.mozilla/firefox/fractal_profile

# Install Fractal wrapper script to run Firefox into /usr/bin
COPY start-firefox.sh /usr/bin/start-firefox
RUN chmod +x /usr/bin/start-firefox

# Setup Fractal application symlink
RUN ln -sf /usr/bin/start-firefox /usr/bin/fractal-application
