web: waitress-serve --url-scheme=https --port=$PORT entry:app
# launch a celery worker dyno with loglevel INFO. This gives us some extra info on when a task 
# is processed, its runtime, and its return values.
celery: celery --app entry.celery worker --pool gevent --concurrency $NUM_WORKERS --loglevel INFO
