web: waitress-serve --url-scheme=https --port=$PORT entry:app
# see worker_manager.py for the thin-wrapper we have implemented around celery workers
celery: python worker_manager.py --num_workers $NUM_WORKERS --pool gevent --worker_concurrency $WORKER_CONCURRENCY
