# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  

  config.vm.define :win10 do |wincfg|
    wincfg.vm.box = "win10-dev.box"
    wincfg.vm.communicator = "winrm"
  end

  # This definition is used to create the local vm box, win10-dev.box
  # To create another box https://www.vagrantup.com/docs/virtualbox/boxes.html
  config.vm.define "win10-download" do |wincfgdown|
    wincfgdown.vm.box = "gusztavvargadr/windows-10"
    wincfgdown.vm.communicator = "winrm"
    wincfgdown.vm.provision "shell", path: "vagrant/scripts/install.ps1"
  end

  config.vm.define :ubuntu do |ubuntucfg|
    ubuntucfg.vm.box = "ubuntu/bionic64"
    ubuntucfg.vm.provision "shell", path: "vagrant/scripts/install.sh"
  end
  

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 8192
    v.cpus = 6
    v.customize ["modifyvm", :id, "--vram", "64"]
  end
  
end
