#!/bin/bash

set -e
err_report() {
  echo "Error at $BASH_SOURCE on line $1!"
}
trap 'err_report $LINENO' ERR

# Get directory of this bash script, follow symlinks as well
DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" >/dev/null 2>&1 && pwd )"
# The repo's root is the parent of this directory
REPO="$(dirname "$DIR")"

# Kill all docker mandelboxs
docker kill $(docker ps -q) || true

# Remove all docker mandelboxs
docker rm $(docker ps -a -q) || true

# Kill host-service
sudo kill $(ps -A | grep host-service | awk '{print $1}') || true

# Create new host service
cd "$REPO/host-service"
screen -mdS host-service bash -c 'make run &> ~/host-service.log'

# Create docker mandelbox image
cd "$REPO/mandelboxes"
./build_local_mandelbox_image.sh browsers/chrome

# Wait for host service
while ! sudo lsof -i :4678 &>/dev/null; do
  sleep 0.1
  if ! screen -S host-service -Q select . &>/dev/null; then
    echo "Host service died for some reason! Host Service Logs:"
    echo "$ cd \"$REPO/host-service\" && make run"
    cat ~/host-service.log
    exit 1
  fi
  echo "Waiting for host service..."
done

# Start running the mandelbox,
# And Start off with journalctl logs though
sleep 0.25
expect <(cat <<'EOF'
log_user 0
spawn sudo ./run_local_mandelbox_image.sh browsers/chrome
send "tail -F /usr/share/fractal/server.log\r"
interact
EOF
)

