# See stage 0 of the base dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM fractal/build-assets:$BuildAssetPackage as build-assets
FROM fractal/base:current-build as fractal-browsers-chrome

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Google Chrome dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    fonts-liberation \
    xdg-utils \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Google Chrome installer
RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Install Google Chrome
RUN apt-get update && apt-get install --no-install-recommends -y \
    google-chrome-stable \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set default browser
RUN su - fractal -c \
    "xdg-mime default google-chrome.desktop text/html \
    && xdg-mime default google-chrome.desktop x-scheme-handler/http \
    && xdg-mime default google-chrome.desktop x-scheme-handler/https \
    && xdg-mime default google-chrome.desktop x-scheme-handler/about"

# Configure Chrome Policies
# For details regarding the options, see:
# https://gist.github.com/meets2tarun/2161e544f4c458c2f07641cafbdd186d
RUN mkdir -p /etc/opt/chrome/policies/managed \
    && echo {} \
    # Whitelist streamed URI protocols (zoommtg,slack.spotify,discord)
    | jq '.URLWhitelist=["zoommtg://*","slack://*","spotify://*","discord://*"]' \
    # Disable search suggestions (as a workaround to improve URL bar
    # keyboard input until we can fork the browser and fix it)
    | jq '.SearchSuggestEnabled=false' \
    # Disable background apps (to prevent apps like Superhuman from
    # indefinitely blocking mandelbox shutdown).
    | jq '.BackgroundModeEnabled=false' \
    # Disable the file selection dialog to hide the mandelbox filesystem
    | jq '.AllowFileSelectionDialogs=false' \
    > /etc/opt/chrome/policies/managed/FractalPolicies.json

# Install Google Chrome extensions
COPY install-extensions.sh /usr/bin/install-extensions.sh
RUN chmod +x /usr/bin/install-extensions.sh && /usr/bin/install-extensions.sh

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/google-chrome"

# Don't show first run popup
RUN su - fractal -c "touch /home/fractal/.config/google-chrome/'First Run'"

# Install Whist wrapper script to run Google Chrome into /usr/bin
ENV WHIST_COOKIE_UPLOAD_TARGET="chrome"
COPY start-chrome.sh /usr/bin/start-chrome
RUN chmod +x /usr/bin/start-chrome
RUN ln -sf /usr/bin/start-chrome /usr/bin/fractal-application

# Install Whist Protocol binaries and helper files (if necessary)
COPY --from=build-assets protocol/* /usr/share/fractal/bin/
