# See stage 0 of the base Dockerfile for an explanation of this build stage.
ARG BuildAssetPackage "protocol"
FROM whist/build-assets:$BuildAssetPackage as build-assets

#########################################################
# Chrome Build Stage
#########################################################

FROM whisthq/browsers/base-chromium:current-build as whist-browsers-chrome

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Google Chrome dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    fonts-liberation \
    xdg-utils \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Google Chrome installer
RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Install Google Chrome
RUN apt-get update && apt-get install --no-install-recommends -y \
    google-chrome-stable \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set default browser
RUN su - whist -c \
    "xdg-mime default google-chrome.desktop text/html \
    && xdg-mime default google-chrome.desktop x-scheme-handler/http \
    && xdg-mime default google-chrome.desktop x-scheme-handler/https \
    && xdg-mime default google-chrome.desktop x-scheme-handler/about"

# Configure Chrome Policies
# For details regarding the options, see:
# https://gist.github.com/meets2tarun/2161e544f4c458c2f07641cafbdd186d
RUN mkdir -p /etc/opt/chrome/policies/managed \
    && echo {} \
    # Whitelist streamed URI protocols (zoommtg,slack,spotify,discord)
    | jq '.URLWhitelist=["zoommtg://*","slack://*","spotify://*","discord://*"]' \
    # Disable search suggestions (as a workaround to improve URL bar
    # keyboard input until we can fork the browser and fix it)
    | jq '.SearchSuggestEnabled=false' \
    # Disable background apps (to prevent apps like Superhuman from
    # indefinitely blocking mandelbox shutdown).
    | jq '.BackgroundModeEnabled=false' \
    # Allow the file selection dialog to enable file uploads
    | jq '.AllowFileSelectionDialogs=true' \
    > /etc/opt/chrome/policies/managed/WhistPolicies.json

# Configure teleport extension and native messaging
RUN mkdir -p /etc/opt/chrome/native-messaging-hosts \
    && echo {} \
    | jq '.name="whist_teleport_extension_host"' \
    | jq '.description="Whist Teleport Chromium Extension Host"' \
    | jq '.path="/opt/teleport/chrome-extension-host"' \
    | jq '.type="stdio"' \
    # This ID is a hash of the path to the Teleport Chrome extension.
    # It will need to be updated if the path ever changes.
    | jq '.allowed_origins[0]="chrome-extension://gilacbinnkddlokepdofmojhijgileoj/"' \
    > /etc/opt/chrome/native-messaging-hosts/whist_teleport_extension_host.json

# Create default config paths
# Don't show first run popup
RUN mkdir -p /home/whist/.config/google-chrome \
    && touch /home/whist/.config/google-chrome/'First Run' \
    && chown whist:whist /home/whist/.config/google-chrome{,/'First Run'}

# Script to install Chrome extensions
COPY --chmod=555 install-extension.sh /usr/bin/install-extension.sh

# Install Whist wrapper script to run Google Chrome into /usr/bin
ENV WHIST_DEST_BROWSER="chrome"
COPY start-chrome.sh /usr/bin/start-chrome
RUN chmod +x /usr/bin/start-chrome && ln -sf /usr/bin/start-chrome /usr/bin/whist-application

# If needed, install WhistServer and helpers. Must be last step.
COPY --from=build-assets protocol/* /usr/share/whist/
