import { OperatingSystem, FractalWindowsDirectory } from "shared/types/client"
import { FractalApp } from "shared/types/ui"
import { FractalNodeEnvironment } from "shared/types/config"
import { SVGConverter } from "shared/utils/files/images"
import { debugLog } from "shared/utils/general/logging"

// Import with require() packages that require Node 10 experimental
const fs = require("fs")
const os = require("os")

export const createDirectorySync = (
    filePath: string,
    directoryName: string
): boolean => {
    /*
        Description:
            Creates a directory on the user's computer. 
        
        Usage:
            To create a directory called "Folder" in "C:\\User\\Fake_User", call createDirectorySync("C:\\User\\Fake_User", "Folder")

        Arguments:
            filePath (string): Folder that the new directory should be placed in
            directoryName (string): Name of new directory
        
        Returns:
            success: True/False if the directory was created successfully
    */

    // If the base file path does not exist, return false
    if (!fs.existsSync(filePath) && fs.lstatSync(filePath).isDirectory()) {
        return false
    }

    // If the directory already exists, return true
    if (
        fs.existsSync(`${filePath}${directoryName}`) &&
        fs.lstatSync(`${filePath}${directoryName}`).isDirectory()
    ) {
        return true
    }

    // If the directory doesn't exist yet, create it
    fs.mkdirSync(`${filePath}${directoryName}`)
    return true
}

export const createShortcutName = (appName: string): string => {
    /*
        Description:
            Generates a shortcut name for consistency

        Arguments:
            appName (string): Name of original app, i.e. "Figma" or "Google Chrome"
        
        Returns:
            name (string): Name of shortcut
    */
    return `${appName} Fractalized`
}

export const createShortcut = async (
    app: FractalApp,
    outputPath: string
): Promise<boolean> => {
    /*
        Description:
            Creates a shortcut to the Fractal streamed app and stores the shortcut in a specified directory

        Arguments:
            app (FractalApp): App to create shortcut to
            outputPath (string): Folder that the shortcut should be placed in. If not specified, defaults to Desktop.
        
        Returns:
            success (boolean): True/False if shortcut was created successfully
    */

    const createDesktopShortcut = require("create-desktop-shortcuts")

    const platform: OperatingSystem = os.platform()
    // appURL is the protocol that the shortcut should run the open Fractal
    const appURL = `fractal://${app.app_id.toLowerCase().replace(/\s+/g, "-")}`

    if (platform === OperatingSystem.MAC) {
        debugLog("Mac shortcuts not yet implemented")
        return false
    }
    if (platform === OperatingSystem.WINDOWS) {
        // Points to the folder where windows.vbs is located (shortcut creation code)
        const vbsPath = `${require("electron")
            .remote.app.getAppPath()
            .replace(
                "app.asar",
                "app.asar.unpacked"
            )}\\node_modules\\create-desktop-shortcuts\\src\\windows.vbs`

        // Convert SVG into a .ico ArrayBuffer
        const buffer = await SVGConverter.convertToIco(app.logo_url)

        // Create directory called /icons to store the .ico if it doesn't already exist
        createDirectorySync(FractalWindowsDirectory.ROOT_DIRECTORY, "icons")
        const icoPath = `${FractalWindowsDirectory.ROOT_DIRECTORY}\\icons\\${app.app_id}.ico`
        // Write .ico into directory
        fs.writeFileSync(icoPath, buffer)
        // Save shortcut in outputPath
        const success = createDesktopShortcut({
            windows: {
                outputPath: outputPath,
                filePath: appURL,
                name: createShortcutName(app.app_id),
                vbsPath:
                    process.env.NODE_ENV === FractalNodeEnvironment.DEVELOPMENT
                        ? null
                        : vbsPath,
                icon: icoPath,
            },
        })
        // Fire callback with shortcut creation success True/False
        return success
    }
    debugLog(`no suitable os found, instead got ${platform}`)
    return false
}

export const checkIfShortcutExists = (shortcut: string): boolean => {
    /*
        Description:
            Checks to see if the user has the shortcut installed in their Desktop or Programs/Application folder.

        Arguments:
            shortcut (string): Name of shortcut (generated by createShortcutName)
        
        Returns:
            exists (boolean): True/False if the shortcut exists
    */
    const platform = os.platform()
    try {
        if (platform === OperatingSystem.MAC) {
            debugLog("mac shortcuts not yet implemented")
            return false
        }
        if (platform === OperatingSystem.WINDOWS) {
            // Check the desktop folder and Start Menu Programs folder
            const windowsDesktopPath = `${FractalWindowsDirectory.DESKTOP}${shortcut}.lnk`
            const windowsStartMenuPath = `${FractalWindowsDirectory.START_MENU}Fractal\\${shortcut}.lnk`

            const exists =
                fs.existsSync(windowsDesktopPath) ||
                fs.existsSync(windowsStartMenuPath)
            return exists
        }
        debugLog(`no suitable os found, instead got ${platform}`)
        return false
    } catch (err) {
        debugLog(err)
        return false
    }
}

export const createWindowsShortcuts = async (
    app: FractalApp,
    desktop = true
): Promise<boolean> => {
    const startMenuPath = `${FractalWindowsDirectory.START_MENU}Fractal\\`
    let desktopSuccess = true
    let startMenuSuccess = true

    // Create a Fractal directory in the Start Menu if one doesn't exist
    if (!createDirectorySync(FractalWindowsDirectory.START_MENU, "Fractal")) {
        return false
    }

    if (desktop) {
        desktopSuccess = await createShortcut(
            app,
            FractalWindowsDirectory.DESKTOP
        )
    }

    startMenuSuccess = await createShortcut(app, startMenuPath)

    return desktopSuccess || startMenuSuccess
}

export const deleteShortcut = (app: FractalApp) => {
    /*
        Description:
            Creates a shortcut to the Fractal streamed app and stores the shortcut in a specified directory

        Arguments:
            app (FractalApp): App to create shortcut to
            outputPath (string): Folder that the shortcut should be placed in. If not specified, defaults to Desktop.
        
        Returns:
            success (boolean): True/False if shortcut was created successfully
    */

    const shortcut = createShortcutName(app.app_id)
    const platform: OperatingSystem = os.platform()

    if (platform === OperatingSystem.MAC) {
        debugLog("Mac shortcuts not yet implemented")
    }
    if (platform === OperatingSystem.WINDOWS) {
        // Points to the folder where windows.vbs is located (shortcut creation code)
        // Check the desktop folder and Start Menu Programs folder
        const windowsDesktopPath = `${FractalWindowsDirectory.DESKTOP}${shortcut}.lnk`
        const windowsStartMenuPath = `${FractalWindowsDirectory.START_MENU}Fractal\\${shortcut}.lnk`

        fs.unlinkSync(windowsDesktopPath)
        fs.unlinkSync(windowsStartMenuPath)
    }
    debugLog(`no suitable os found, instead got ${platform}`)
}
