FROM fractal/base:current-build

# Force failure on non-zero exit code for commands with a pipe in them
SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]

# Install Google Chrome dependencies explicitly
RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxi6 \
    fonts-liberation \
    xdg-utils \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download Google Chrome installer
RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Install Google Chrome
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     google-chrome-stable \
#     && apt-get autoremove -y \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*
# Check available versions here: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
# This NEEDS to be reverted to the above latest stable as soon as Google fixes the issues, or as soon as we find a workaround
ARG CHROME_VERSION="91.0.4472.164-1"
RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
    && apt-get install --no-install-recommends -y /tmp/chrome.deb \
    && rm /tmp/chrome.deb

# Set default browser
RUN su - fractal -c \
    "xdg-mime default google-chrome.desktop text/html \
    && xdg-mime default google-chrome.desktop x-scheme-handler/http \
    && xdg-mime default google-chrome.desktop x-scheme-handler/https \
    && xdg-mime default google-chrome.desktop x-scheme-handler/about"

# Install Google Chrome extensions
COPY install-extensions.sh /usr/bin/install-extensions.sh
RUN chmod +x /usr/bin/install-extensions.sh
RUN /usr/bin/install-extensions.sh

# Create default config paths
RUN su - fractal -c "mkdir -p /home/fractal/.config/google-chrome"

# Don't show first run popup
RUN su - fractal -c "touch /home/fractal/.config/google-chrome/'First Run'"

# Install Fractal wrapper script to run Google Chrome into /usr/bin
COPY start-chrome.sh /usr/bin/start-chrome
RUN chmod +x /usr/bin/start-chrome

# Setup Fractal application symlink
RUN ln -sf /usr/bin/start-chrome /usr/bin/fractal-application
